version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/tmp/maildir
    volumes:
      - maildir:/tmp/maildir
    networks:
      - mailhog-network
    logging:
      driver: "none"

networks:
  mailhog-network:
    name: mailhog-network
    driver: bridge

volumes:
  maildir: